{
	parserClass="com.github.intellij6502.parser.Asm6502Parser"
	stubParserClass="com.github.intellij6502.parser.GeneratedParserUtilBase"

	extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

	psiClassPrefix="Asm6502"
	psiImplClassSuffix="Impl"
	psiPackage="com.github.intellij6502.psi"
	psiImplPackage="com.github.intellij6502.psi.impl"

	elementTypeHolderClass="com.github.intellij6502.psi.Asm6502Type"
	elementTypeClass="com.github.intellij6502.psi.Asm6502ElementType"
	tokenTypeClass="com.github.intellij6502.psi.Asm6502TokenType"
}

asm6502File ::= item_*

private item_ ::= (label_declaration|number|ADDRESS|DIRECTIVE|MNEMONIC|COMMENT|CRLF)

// labels
label_declaration ::= (LABEL)

// numbers
number ::= (HEXADECIMAL_VALUE|DECIMAL_VALUE|BINARY_VALUE)

