{
	parserClass="com.github.intellij6502.parser.Asm6502Parser"
	stubParserClass="com.github.intellij6502.parser.GeneratedParserUtilBase"

	extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

	psiClassPrefix="Asm6502"
	psiImplClassSuffix="Impl"
	psiPackage="com.github.intellij6502.psi"
	psiImplPackage="com.github.intellij6502.psi.impl"

	elementTypeHolderClass="com.github.intellij6502.psi.Asm6502Type"
	elementTypeClass="com.github.intellij6502.psi.Asm6502ElementType"
	tokenTypeClass="com.github.intellij6502.psi.Asm6502TokenType"
}

asm6502File ::= item_*
private item_ ::= (LABEL|directive_command|mnemonic_command|COMMENT|CRLF)

// directive command
directive_command ::= DIRECTIVE directive_argument

directive_argument ::= (DIRECTIVE_NUMBER | DIRECTIVE_STRING)

// mnemonic command
mnemonic_command ::= (MNEMONIC mnemonic_argument)
mnemonic_argument ::= (number | ADDRESS | indirect)

// indirect
indirect ::= (OPEN_PARENTHESIS ADDRESS CLOSE_PARENTHESIS)

// numbers
number ::= (HEXADECIMAL_VALUE|DECIMAL_VALUE|BINARY_VALUE)
